#!/usr/bin/env bash
# Script to install nginx server
sudo apt -y update
sudo apt -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n	rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart
