#!/usr/bin/env bash
#Displays numbers from 1 to 100 - Fizz Buzz Challenge

x=1
while [ $x -le 100 ]
do
	if (( x % 3 == 0 && x % 5 == 0 )) 
	then
		echo "Fizzbuzz"
	elif (( x % 5 == 0 ))
	then
		echo "Buzz"
	elif (( x % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$x"
	fi	
	x=$(( x + 1 ))
done
